### ISSUE TITLE
Redundant lazy constraint

### ISSUE THREAD

**Issue by blegat** [jump-dev/GLPK.jl#153] opened 2020-10-04 11:42 UTC
Consider the following model on JuMP v0.21:
```julia
import GLPK
mip_solver = optimizer_with_attributes(GLPK.Optimizer, "msg_lev" => 4, "tm_lim" => 15.0)

m = Model(mip_solver)

@variable(m, x >= 0, Int)
@variable(m, y >= 0)

@objective(m, Max, 3x + y)

@constraint(m, 3x + 2y <= 10)

MOI.set(m, MOI.LazyConstraintCallback(), cb -> begin
    con = @build_constraint(6x <= 18)
    MOI.submit(m, MOI.LazyConstraint(cb), con)
end)

JuMP.optimize!(m)
```
and the seemingly equivalent model on JuMP v0.18:
```julia
import GLPK
mip_solver = GLPKMathProgInterface.GLPKSolverMIP(msg_lev=4, tm_lim=15.0)

m = Model(solver=mip_solver)
@variable(m, x >= 0, Int)
@variable(m, y >= 0)

@objective(m, Max, 3x + y)

@constraint(m, 3x + 2y <= 10)

addlazycallback(m, cb -> begin
    @lazyconstraint(cb, 6x <= 18)
end, fractional=true)

JuMP.solve(m)
```
The first one reaches time limit while the second finishes successfully.
Where does the different come from ?
The MPB wrapper had the following condition:
https://github.com/JuliaOpt/GLPKMathProgInterface.jl/blob/26f755770f8b70a81ade83cd1e6d85fa8c8254c9/src/GLPKInterfaceMIP.jl#L305-L309
which, in case the current solution was satisfied by the callback, would actually not give the callback to GLPK.
I guess other solvers supporting lazy callbacks do that internally so I was wondering whether we could do that in the GLPK wrapper or add a warning in MOI doc.

**Comment by odow** [comment] 2020-10-04 20:08
Your examples are an incorrect usage of a callback.

Users should check that the cut actually cuts off the current solution:
https://github.com/jump-dev/JuMP.jl/blob/709d41b78e56efb4f2c54414266b30932010bd5a/examples/callbacks.jl#L31-L37

**Comment by blegat** [comment] 2020-10-04 20:51
Yes, it was in Pavito and apparently it relied on the fact that apparently all solver or their MPB wrapper handle it

**Comment by odow** [comment] 2020-10-04 23:33
I guess GLPK's termination rule is: if you have an integer feasible optimal solution, and the user did not add any new lazy constraints in this iteration, stop.

The whole point of lazy constraints is that you get to look at the primal solution and decide whether to add a new constraint. If you have a callback like your example, you should just add `@constraint(model, 6x <= 18)`.

Closing because this is expected behavior, matches the documentation, and appears to be an issue in Pavito.

**Closed by odow** 2020-10-04 23:33 UTC
